const Premium_match_data = [
    {
        id: 1,
        img: require('../../../assets/image/premium_match_1.png'),
        name: "Prachi Singh",
        age: 23,
        height: "4’8”",
        language: "Bengali",
        job: "Nurse",
        cast: "Hindu",
        address: "West Bengal ",
        country: "India",
        about: "I am a good listener but passionate about laughter, connection, and creating unforgettable memories",
        hobbies: ["Cricket", "Dancing", "Foodie", "Football"],
        profileID:"SH09876543212",
        birthDate:'Birth on 12/08/1999',
        marriedprofile:"Never Married",
        community:"Rajput",
        ditePref:"Non - Vegetarian",
        contactNo: "+91 0987654321",
        email:"Prachi@gmail.com",
        profession: "Currently not working",
        companyName:"BM Coder",
        qulification: "MCA",
        educationfield:"Design",
        collegename:"Silver Oak",
        newProfile: true
    },
    {
        id: 2,
        img: require('../../../assets/image/premium_match_2.png'),
        name: "Krishna",
        age: 23,
        height: "4’5”",
        language: "Gujarati",
        job: "Nurse",
        cast: "Hindu",
        address: "Ahmedabad ",
        country: "India",
        about: "I am a good listener but passionate about laughter, connection, and creating unforgettable memories",
        hobbies: ["Cricket", "Dancing", "Foodie", "Football"],
        profileID:"SH09876543212",
        birthDate:'Birth on 12/08/1999',
        marriedprofile:"Married",
        community:"Rajasthani",
        ditePref:"Non - Vegetarian",
        contactNo: "+91 0987654321",
        email:"krishna@gmail.com",
        profession: "Currently not working",
        companyName:"BM Coder",
        qulification: "MCA",
        educationfield:"Design",
        collegename:"GLS",
        newProfile: true

    },
    {
        id: 3,
        img: require('../../../assets/image/premium_match_3.png'),
        name: "Neha Singh",
        age: 20,
        height: "5’2”",
        language: "Marathi",
        job: "UI / UX Designer",
        cast: "Hindu",
        address: "Mumbai ",
        country: "India",
        about: "I am a good listener but passionate about laughter, connection, and creating unforgettable memories",
        hobbies: ["Cricket", "Dancing", "Foodie", "Football"],
        profileID:"SH09876543212",
        birthDate:'Birth on 12/08/1999',
        marriedprofile:"Never Married",
        community:"Marathi",
        ditePref:"Non - Vegetarian",
        contactNo: "+91 912551232",
        email:"neha@gmail.com",
        profession: "Currently working",
        companyName:"BM Coder",
        qulification: "MCA",
        educationfield:"Design",
        collegename:"President College",
        newProfile: false

    },
    {
        id: 4,
        img: require('../../../assets/image/premium_match_4.jpg'),
        name: "Rajesh Kumar",
        age: 28,
        height: "5’8”",
        language: "Hindi",
        job: "Software Engineer",
        cast: "Hindu",
        address: "Bangalore",
        country: "India",
        about: "Passionate coder and fitness enthusiast.",
        hobbies: ["Coding", "Reading", "Gym", "Travel"],
        profileID: "SH09876543234",
        birthDate: 'Birth on 01/05/1995',
        marriedprofile: "Never Married",
        community: "Kshatriya",
        ditePref: "Vegetarian",
        contactNo: "+91 9876543210",
        email: "rajesh.kumar@gmail.com",
        profession: "Currently working",
        companyName: "Tech Solutions",
        qulification: "B.Tech",
        educationfield: "Computer Science",
        collegename: "IIT Delhi",
        newProfile: true

    },
    {
        id: 5,
        img: require('../../../assets/image/premium_match_5.jpg'),
        name: "Aarti Sharma",
        age: 25,
        height: "5’5”",
        language: "Punjabi",
        job: "Doctor",
        cast: "Hindu",
        address: "Chandigarh",
        country: "India",
        about: "Caring and compassionate healthcare professional.",
        hobbies: ["Painting", "Cooking", "Cycling"],
        profileID: "SH09876543245",
        birthDate: 'Birth on 15/02/1998',
        marriedprofile: "Never Married",
        community: "Brahmin",
        ditePref: "Vegetarian",
        contactNo: "+91 8765432198",
        email: "aarti.sharma@gmail.com",
        profession: "Currently working",
        companyName: "City Hospital",
        qulification: "MBBS",
        educationfield: "Medicine",
        collegename: "PGI Chandigarh",
        newProfile: false

    },
    {
        id: 6,
        img: require('../../../assets/image/premium_match_6.jpg'),
        name: "Aditya Mehta",
        age: 30,
        height: "6’0”",
        language: "Gujarati",
        job: "Entrepreneur",
        cast: "Jain",
        address: "Surat",
        country: "India",
        about: "Businessman with a passion for philanthropy.",
        hobbies: ["Golf", "Reading", "Traveling"],
        profileID: "SH09876543256",
        birthDate: 'Birth on 20/06/1993',
        marriedprofile: "Never Married",
        community: "Jain",
        ditePref: "Vegetarian",
        contactNo: "+91 9988776655",
        email: "aditya.mehta@gmail.com",
        profession: "Currently working",
        companyName: "Mehta Industries",
        qulification: "MBA",
        educationfield: "Business Management",
        collegename: "IIM Ahmedabad",
        newProfile: true

    },
    {
        id: 7,
        img: require('../../../assets/image/premium_match_7.jpg'),
        name: "Pooja Patel",
        age: 27,
        height: "5’3”",
        language: "Hindi",
        job: "Graphic Designer",
        cast: "Patel",
        address: "Vadodara",
        country: "India",
        about: "Creative designer with a love for art.",
        hobbies: ["Sketching", "Music", "Dance"],
        profileID: "SH09876543267",
        birthDate: 'Birth on 10/10/1996',
        marriedprofile: "Never Married",
        community: "Patidar",
        ditePref: "Non - Vegetarian",
        contactNo: "+91 9988665544",
        email: "pooja.patel@gmail.com",
        profession: "Currently working",
        companyName: "Design Hub",
        qulification: "BFA",
        educationfield: "Fine Arts",
        collegename: "MSU Baroda",
        newProfile: false
    },
];

export default Premium_match_data;
