const Icons = {
    splashLogo: require('../../assets/logos/app_logo.jpg'),
    bagIcon: require('../../assets/icons/bag_icon.png'),
    educationIcon: require('../../assets/icons/education_icon.png'),
    googleIcon: require('../../assets/icons/google_logo.png'),
    locationIcon: require('../../assets/icons/location_icon.png'),
    profileIcon: require('../../assets/icons/profile_icon.png'),
    profileIcon2: require('../../assets/icons/profile_icon_2.png'),
    notificationBell: require('../../assets/icons/bell-02.png'),
    blueTickIcon: require('../../assets/icons/blue_tick.png'),
    HomeTab: require('../../assets/icons/home-2.png'),
    userTab: require('../../assets/icons/users.256x214.png'),
    emailTab: require('../../assets/icons/email.png'),
    chatTab: require('../../assets/icons/messages-2.png'),
    PremiumTab: require('../../assets/icons/Group.png'),
    bitrhIcon: require('../../assets/icons/birthIcon.png'),
    locationIcon2: require('../../assets/icons/locationIcon.png'),
    personIcon: require('../../assets/icons/personIcon.png'),
    groupIcon: require('../../assets/icons/groupIcon.png'),
    swipIcon: require('../../assets/icons/swipe_icon.png'),
    usercircle: require('../../assets/icons/user-avatar.png'),
    support: require('../../assets/icons/24-hours-support.png'),
    blogIcon: require('../../assets/icons/credit-card.png'),
    faqIcon: require('../../assets/icons/receip.png'),
    notifyIcon: require('../../assets/icons/notification.png'),
    douIcon: require('../../assets/icons/document-text.png'),
    exitIcon: require('../../assets/icons/log-out.png'),
    vectorIcon: require('../../assets/icons/receipt.221x256.png'),
    filterIcon: require('../../assets/icons/filter.png'),
    VideorecordIcon: require('../../assets/icons/video.png'),
    phoneIcon: require('../../assets/icons/telephone.png'),
    incomingCallIcon: require('../../assets/icons/phone-incoming.png'),
    outgingCallIcon: require('../../assets/icons/phone-outging.png'),
    missedCallIcon: require('../../assets/icons/missed-call.png'),
    noProfileUser: require('../../assets/icons/user.png'),
    blueTickIcon2: require('../../assets/icons/blue_tick-1.png'),
}

export default Icons;